apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  database-password: cGFzc3dvcmRfMjAyNA==
  api-key: c2stMTIzNDU2Nzg5MGFiY2RlZjEyMzQ1Njc4OTA=
  jwt-secret: and0LXNlY3JldC1rZXktMjAyNA==
  aws-access-key: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  aws-secret-key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
